server:
  port: 9000

spring:
  data-source:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

jwt:
  secret: mittul123
